#' Reference H3K27ac read counts for consensus peaks.
#'
#' A dataset containing read counts generated using H3K27ac data from purified brain cell
#' types, for consensus peaks generated by the CHAS-MF function UnionPeaks(). This dataset is
#' used as an example for the CHAS-MF tutorial
#'
#' @format A counts per million matrix with 251345 rows and 12 variables, with
#' rows labelling consensus peaks and columns labelling cell-type samples.
#'
#' @source Generated using data from \url{https://www.nature.com/articles/s41593-018-0253-7}
#' and \url{https://github.com/nottalexi/brain-cell-type-peak-files/tree/master/H3K27ac}
"AD_unionCounts_ref"

